

CREATE TABLE IF NOT EXISTS links (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	link_name VARCHAR(255) NOT NULL,
	alias VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS clicks (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	link_id INTEGER NOT NULL,
	click_date DATETIME NOT NULL,
	FOREIGN KEY (link_id) REFERENCES links(id) ON DELETE CASCADE
);
